import { FeedProps } from ".";

export const mockFeed: FeedProps = {
  messages: [
    {
      id: "1",
      userId: "1",
      content: "This is a raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "/img/wiz_avatar.png",
    },
    {
      id: "2",
      userId: "2",
      content: "This is another raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "3",
      userId: "3",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "4",
      userId: "4",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "5",
      userId: "5",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "6",
      userId: "6",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "7",
      userId: "7",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "8",
      userId: "8",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
    {
      id: "9",
      userId: "9",
      content: "This is a third raven",
      username: "Jon Snow",
      date: "2 hours ago",
      userAvatar: "https://i.pravatar.cc/300",
    },
  ],
};